-- Seed Data for 150 CAT Topics
-- Truncate existing to prevent duplicates if re-run
TRUNCATE TABLE topics CASCADE;

INSERT INTO topics (day_number, topic_name, section, order_index) VALUES
(1, 'Ratio and Proportion', 'QUANT', 1),
(2, 'Mixtures and Solutions', 'QUANT', 2),
(3, 'Percentages', 'QUANT', 3),
(4, 'Variation', 'QUANT', 4),
(5, 'DI Bar, Line Pie Chart', 'LRDI', 5),
(6, 'DI Special Charts', 'LRDI', 6),
(7, 'Approach to RC', 'VARC', 7),
(8, 'Identifying Central Idea of Passage', 'VARC', 8),
(9, 'Introduction to Profit, Loss and Discount', 'QUANT', 9),
(10, 'Faulty Balances and Measures', 'QUANT', 10),
(11, 'Interest', 'QUANT', 11),
(12, 'Installments', 'QUANT', 12),
(13, 'DI Data over the years', 'LRDI', 13),
(14, 'DI Cumulative DI', 'LRDI', 14),
(15, 'DI Table with Missing Values', 'LRDI', 15),
(16, 'Relative Velocity', 'QUANT', 16),
(17, 'Circular Tracks', 'QUANT', 17),
(18, 'Races and Headstarts', 'QUANT', 18),
(19, 'Boats and Escalators', 'QUANT', 19),
(20, 'Informative Reading Comprehensions', 'VARC', 20),
(21, 'Persuasive RCs', 'VARC', 21),
(22, 'Circular Arrangement', 'LRDI', 22),
(23, 'Arrangement Across Levels', 'LRDI', 23),
(24, 'Einstein''s Puzzle', 'LRDI', 24),
(25, 'Seating Arrangement - People facing different directions', 'LRDI', 25),
(26, 'Square Seating Arrangement', 'LRDI', 26),
(27, 'Inferences', 'VARC', 27),
(28, 'RC''s having close options', 'VARC', 28),
(29, 'Time and Work', 'QUANT', 29),
(30, 'Pipes and Cisterns', 'QUANT', 30),
(31, 'Team Selection: Advanced', 'LRDI', 31),
(32, 'Games and Tournaments', 'LRDI', 32),
(33, 'Introduction to Triangles', 'QUANT', 33),
(34, 'Area of Triangles', 'QUANT', 34),
(35, 'Internal and External Angle Bisector Theorem', 'QUANT', 35),
(36, 'Congruency and Similarity of Triangles', 'QUANT', 36),
(37, 'Apollonius Theorem', 'QUANT', 37),
(38, 'Number of Triangles given perimeter', 'QUANT', 38),
(39, 'Routes and Networks', 'LRDI', 39),
(40, 'Scheduling', 'LRDI', 40),
(41, 'Quant based DI', 'LRDI', 41),
(42, 'Para Summary', 'VARC', 42),
(43, 'Summary Option Elimination Strategy', 'VARC', 43),
(44, 'Chords and Tangents', 'QUANT', 44),
(45, 'Circumference and Area of Circle', 'QUANT', 45),
(46, 'Alternate Segment Theorem', 'QUANT', 46),
(47, 'Quadrilaterals', 'QUANT', 47),
(48, 'Polygons', 'QUANT', 48),
(49, 'Mensuration of Solids', 'QUANT', 49),
(50, 'Mensuration of Solids 2', 'QUANT', 50),
(51, 'TITA Parajumbles', 'VARC', 51),
(52, 'Identifying Links using Transition Words', 'VARC', 52),
(53, 'Out of Context', 'VARC', 53),
(54, 'PJs and OOC using grammar rules', 'VARC', 54),
(55, 'Linear Equations in 3 Variables', 'QUANT', 55),
(56, 'Special Linear Equations', 'QUANT', 56),
(57, 'Para Completion (Sentence Insertion)', 'VARC', 57),
(58, 'Eliminating options Para Insertion', 'VARC', 58),
(59, 'Truth-Lie Concept', 'LRDI', 59),
(60, 'Introduction to Quadratic Equations', 'QUANT', 60),
(61, 'Maxima and Minima', 'QUANT', 61),
(62, 'Factorizing Polynomials', 'QUANT', 62),
(63, 'Inequalities with Modulus', 'QUANT', 63),
(64, 'Area enclosed by Inequalities', 'QUANT', 64),
(65, 'Quant Based LR', 'LRDI', 65),
(66, 'Progressions', 'QUANT', 66),
(67, 'Arithmetic-Geometric Progression', 'QUANT', 67),
(68, 'AM, GM, HM', 'QUANT', 68),
(69, 'Advanced Progressions', 'QUANT', 69),
(70, 'Strengthen or Weaken Conclusion', 'VARC', 70),
(71, 'Introduction to Functions', 'QUANT', 71),
(72, 'Mean, Median and Mode', 'QUANT', 72),
(73, 'Cauchy''s Functional Equations', 'QUANT', 73),
(74, 'DI Venn Diagrams', 'LRDI', 74),
(75, '4-Group Venn Diagrams', 'LRDI', 75),
(76, 'Venn Diagrams - Maxima-Minima', 'LRDI', 76),
(77, 'Surds and Indices', 'QUANT', 77),
(78, 'Logarithms 1', 'QUANT', 78),
(79, 'Logarithms Advanced', 'QUANT', 79),
(80, 'Cyclicity of Factors', 'QUANT', 80),
(81, 'HCF and LCM', 'QUANT', 81),
(82, 'Highest Power of a Number in a Factorial', 'QUANT', 82),
(83, 'Number of Integral Solutions', 'QUANT', 83),
(84, 'Remainder Theorem Basics', 'QUANT', 84),
(85, 'Permutations and Combinations - Basics', 'QUANT', 85),
(86, 'Selection and Arrangement with Repetition', 'QUANT', 86),
(87, 'Partitioning', 'QUANT', 87),
(88, 'Probability 1', 'QUANT', 88),
(89, 'Advanced Probability', 'QUANT', 89),
(90, 'Binomial Theorem', 'QUANT', 90),
(91, 'Averages', 'QUANT', 91),
(92, 'Alligations / Alligation: 3 items', 'QUANT', 92),
(93, 'Successive Percentage Change / Stocks and Shares', 'QUANT', 93),
(94, 'Introduction to Time, Speed and Distance / Clocks', 'QUANT', 94),
(95, 'Data Interpretation Approx Techniques', 'LRDI', 95),
(96, 'DI Bubble Chart / DI Area Chart', 'LRDI', 96),
(97, 'DI Rate of Growth / DI Connecting Data Sets', 'LRDI', 97),
(98, 'DI Table with Incorrect Values', 'LRDI', 98),
(99, 'Logical representation of information', 'LRDI', 99),
(100, 'Linear Arrangement / Square, Complex Arrangement', 'LRDI', 100),
(101, 'Calendars', 'LRDI', 101),
(102, 'Scientific RC / Negative Tone RC', 'VARC', 102),
(103, 'Author Agree or Disagree', 'VARC', 103),
(104, 'Selection with Conditions', 'LRDI', 104),
(105, 'Knock-out Tournaments / Multi-stage Tournaments', 'LRDI', 105),
(106, 'Parallel Lines and Angles / Incenter, Circumcenter, Orthocentre, Centroid', 'QUANT', 106),
(107, 'Basics of Trigonometry / Applications of Trigonometry', 'QUANT', 107),
(108, 'Heights and Distances', 'QUANT', 108),
(109, 'Ratio of Areas of Inscribed Figures', 'QUANT', 109),
(110, 'Coordinate Geometry / Number of Integral Lattice Points', 'QUANT', 110),
(111, 'Introduction to Algebra', 'QUANT', 111),
(112, 'Linear Equations - 2 Variables / Determinant Method', 'QUANT', 112),
(113, '2D Space LRs / Painted Cubes', 'LRDI', 113),
(114, 'RC Structure Based Questions', 'VARC', 114),
(115, 'Tone of Passage', 'VARC', 115),
(116, 'Truth-Liar Seating Arrangement / LR Based on Picking Coins', 'LRDI', 116),
(117, 'Quadratic Equations - Relations between Equations / Range of Possible Values', 'QUANT', 117),
(118, 'Inequalities Basics', 'QUANT', 118),
(119, 'Common Terms in Progressions / Sum of Convergent Series', 'QUANT', 119),
(120, 'Categorization', 'LRDI', 120),
(121, 'Blood Relations / Directions', 'LRDI', 121),
(122, 'Finding Assumptions / Identifying Conclusions', 'VARC', 122),
(123, 'Identifying Components in Critical Reasoning / Flaw in Argument', 'VARC', 123),
(124, 'Evaluating Extra Information / Parallel Reasoning', 'VARC', 124),
(125, 'Even and Odd Functions', 'QUANT', 125),
(126, 'Modified Cauchy''s Equations', 'QUANT', 126),
(127, 'Graphs and Shifting of Graphs', 'QUANT', 127),
(128, 'Surds Advanced (Rationalization) / Number of digits using log', 'QUANT', 128),
(129, 'Divisibility Rules / Introduction to Factors', 'QUANT', 129),
(130, 'Divisions leaving same remainders / Number of trailing zeroes', 'QUANT', 130),
(131, 'Non-zero Last digit of a Factorial / Base Systems', 'QUANT', 131),
(132, 'Fermat Theorem / Wilson''s Theorem', 'QUANT', 132),
(133, 'Euler''s Theorem / Chinese Remainder Theorem', 'QUANT', 133),
(134, 'Advanced Remainder Theorem / Remainders with a Series', 'QUANT', 134),
(135, 'Circular Arrangements', 'LRDI', 135),
(136, 'Inclusion Exclusion Principle / Derangement', 'QUANT', 136),
(137, 'Bayes Theorem', 'QUANT', 137),
(138, 'Probability Based on Dice', 'QUANT', 138),
(139, 'Introduction to Data Sufficiency / Data Sufficiency 3', 'LRDI', 139),
(140, 'Poem RCs / Mixtures and Alligation', 'VARC_QUANT', 140),
(141, 'Profit and Loss', 'QUANT', 141),
(142, 'Time and Work', 'QUANT', 142),
(143, 'Time, Speed and Distance', 'QUANT', 143),
(144, 'Relative Velocity', 'QUANT', 144),
(145, 'Races, Boats and Escalators', 'QUANT', 145),
(146, 'Main idea / Purpose of the passage', 'VARC', 146),
(147, 'Inferences from passage', 'VARC', 147),
(148, 'RC Structure Based Questions', 'VARC', 148),
(149, 'Author''s opinion', 'VARC', 149),
(150, 'Table with Missing Values', 'LRDI', 150);
